### ISSUE TITLE
Guest Signature checkbox to be relocated to Issue from Accept popup window

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#15]
**Issue:**
The checkbox to allow handover of the Permit to a "Guest" Permit Holder can be assigned at the point of Permit Holder accepting the permit.  This means that a Permit Holder can hand over a permit to another person (maybe not even a qualifies PH).  This should be managed at the Permit Issuer level of the organization not the PH.

_**TO BE COMPLETED.....**_

**Comment by jimbrown75** [comment]
Close
