### ISSUE TITLE
PBU cannot be removed or switched off after setting initially

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#16]
This is an item we have been aware of previously, but now we are on v8 we need to have a solution prepared and presented to Shell regarding the PBU.  

The **CURRENT SITUATION** is once the PBU is set in the ICC (i.e. every 24 hours) then it is required in the system for the duration of that ICC until the ICC is Completed.

**ISSUE**
- The PBU is not always required for the whole lifecycle of the ICC.  
- For example is the ICC is moved to EPI, it is almost never required in this state.

**SUGGESTED SOLUTION**
- We require a mechanism to "turn off" the PBU requirement, at any point after the ICC is moved to the Live In Place state.  Somehow we should be able to toggle if it is required or not at any given time.

**Comment by jimbrown75** [comment]
Take forward - need to discuss further
