### ISSUE TITLE
PtW Effectiveness Module Improvements

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#23]
I would like to raise a Change Request to improve the **PtW Effectiveness** module.

Issues we have:
- Poor overview for leaders
- No ICC Review/Audit
- No ability to Search audits/review that have been completed
- No review/sign off by leaders of the review/audits that were completed

Suggestions:
1.  We have committed to re-look at the question set for the PtW Effectiveness module within the SME team...we need to make this happen.
2.  I would like to review an ICC question set within the SME team, I will bring this forward to review
3.  I would like to work with eVision to create better search functionality of the reviews/audits (by whom, on what equipment, date completed, etc.)
4.   I would like to change the workflow to include a signature to "Accept" the review/audit which was completed.  Currently the user completes the review and then signs it off and it goes away as "Completed". I would like to request that we put in more formal structure of review before it is submitted and moved to Completed.

I think we should also poll the SME Team and the PV User Community on other changes/Improvements they would like to see in this space.

@jimbrown75 do you have any thoughts on this before I raise a CR in the SharePoint List?  Or how/when you would like to discuss with the SME Teams/User Community?

**Comment by DANMPV** [comment]
ACTION from UC Call 23 Aug 2017:  Here is the latest version of the PtW Effectiveness Assurance Tool Questions as updated by the PtW/Safe Isolation CoE Team in May 2017 during the Calgary Global F2F session.

[PTW Effectiveness Assurance Tool v1.0.xlsx](https://github.com/jimbrown75/Permit-Vision-Enhancements/files/1249245/PTW.Effectiveness.Assurance.Tool.v1.0.xlsx)

![ptw eff assurance](https://user-images.githubusercontent.com/23561839/29671954-246a5c32-88a8-11e7-8f03-2c120c3accb6.PNG)

**Comment by marlybrown** [comment]
Shared with User Community

**Comment by DANMPV** [comment]
TEST comment: Thanks for that Marly

**Comment by jimbrown75** [comment]
Captured in other thingy gitbub number 593
