### ISSUE TITLE
Site SME Examples of missing translations (German and Dutch) in V8 (17 May)

### ISSUE THREAD

**Issue by MariaDozlicShell** [jimbrown75/Permit-Vision-Enhancements#30]
As shared in the 17th May training huddle, attached are the examples from Felicitas (German) and Wim (Dutch) of the missing German translations in V8 that need fixing before they go ahead and validate translation in V8. Felicitas analysis was that the majority of missing German words is in the new enhancements. Note: This is holding up the Site SME validation efforts. 

Additionally, without these issues being fixed in the tool, the Site SMEs cannot grab the necessary screenshots that can then be used to retrofit the SOU eLearning modules in German and Dutch.

[Examples - German Translation issues in V8.docx](https://github.com/jimbrown75/Permit-Vision-Enhancements/files/1030124/Examples.-.German.Translation.issues.in.V8.docx)

----------------------------------------

From: Felten-Becker, Felicitas SDO-HRD/LMH 
Sent: Thursday, May 18, 2017 11:45 AM
To: Dozlic, Maria M SOPUS-ITD/MP <Maria.Dozlic@shell.com>
Cc: Pereira, Sarah SCAN-ITD/MCH <S.Pereira@shell.com>; Francois, Lynette J SOPUS-ITD/MP <Lynette.francois@shell.com>; Ortega-Cardona, Maria A SDO-DMS/65Q <Maria.Ortega-Cardona@shell.com>; Watermann, Beate SDO-DMS/65Q <beate.watermann@shell.com>
Subject: Translation - Examples of missing translations in V8

Hi Maria, 

As discussed in our call, please find below some examples for the missing translations in V8. I did only a quick check in the draft status (5 minutes). 

After log in:
Site menu:
Draft step of a permit:
Audit Trail
Status / Navigation Bar

Additionlly the new buttons have english tool tips (I don’t know if it is the right word).

I think there are definitly more missing translations. Can you support us to receive a complete translation file (for check) from eVision?

Thanks and kind regards, 
Feli 
[Dutch-Feedback vertaling_5.xlsx](https://github.com/jimbrown75/Permit-Vision-Enhancements/files/1030137/Dutch-Feedback.vertaling_5.xlsx)
[Dutch-ShellDS - Translation corrections sheet.xlsx](https://github.com/jimbrown75/Permit-Vision-Enhancements/files/1030139/Dutch-ShellDS.-.Translation.corrections.sheet.xlsx)

From: Begthel, Wim A SNR-DMS/762 
Sent: Tuesday, May 16, 2017 9:49 AM
To: Dozlic, Maria M SOPUS-ITD/MP <Maria.Dozlic@shell.com>
Cc: Kraan, Edwin R SNV-STO/152 <Edwin.Kraan@shell.com>; van Leeuwen, Henk SNR-DMS/762 <Henk.VanLeeuwen@shell.com>
Subject: Translation review procedure

Maria.

At your request, the first enhancements of V8.

Wim.

**Comment by jimbrown75** [comment]
@MariaDozlicShell 

Hi Maria, I think you may have put this in the wrong GitHub repository. This one is for future enhancements. Can you check please as it wont get the attention in here. Thanks.

Jim

**Comment by MariaDozlicShell** [comment]
Hi I added to the Issues List - thanks for letting me know! - Maria
