### ISSUE TITLE
EPI - Before moving back to Live In Place each point should be ticked off

### ISSUE THREAD

**Issue by jimbrown75** [jimbrown75/Permit-Vision-Enhancements#31]
when moving an EPI isolation back to live in place the IO role should have to do a field check of each point, therefore they should go through the same process as when executing an isolation in the first place. i.e. tick of in the system each point. Perhaps also verification signature too?

**Comment by DANMPV** [comment]
UC suggestion is to NOT have IV also sign.  No specific added value seen in doing so.
