### ISSUE TITLE
When suspending permit add date field for when the permit will next be requried

### ISSUE THREAD

**Issue by jimbrown75** [jimbrown75/Permit-Vision-Enhancements#35]
When suspending permit add date field for when the permit will next be required. This field is searchable in the search page so that Permit Issuers can prepare permits in advance.

**Comment by DANMPV** [comment]
Should not be a Mandatory field.  Optional only

**Comment by DANMPV** [comment]
The date added should not affect the useablebility of the permit post the suggested date.  This date should be an "Expected" use date, not mandatory use.

**Comment by jimbrown75** [comment]
Duplicated with #17
