### ISSUE TITLE
Conflict Flag for ICC points in Draft

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#39]
We would like to request that when an ICC is being drafted or used in the tool, the conflict flag does not look at other ICC with the same point if the ICC is still in Draft state.  Any other state is fine, but remove the search against other ICCs with this point if the ICC is in Draft.

![draft icc flag](https://user-images.githubusercontent.com/23561839/28899917-d1dfd5f0-7830-11e7-87c6-75781ccddbec.PNG)

**Comment by jimbrown75** [comment]
Discussed - flag should appear only if in an ICC that is in state Authorised onwards...
