### ISSUE TITLE
ICC: Test Point Verification 

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#41]
_Request from Tabangao (via Erwin San-Miguel)_

A feature that we want to be included, is the “**Test Point Verification**”. 

Justification: Similar to gas test, test point verification is a requirement by the DSM Process Isolation Standard that a zero-energy confirmation is done before an equipment is handed over to maintenance. 

The request is an additional field similar to gas test, which will stop the Permit Issuer from issuing the permit if the test point confirmation has not been completed. 

This can be via remark or inputting a value of “0” to indicate pressure-free or zero energy.

**Comment by DANMPV** [comment]
Questions I have:

1. Should this be assigned to the permit or the ICC?  It seems a the permit level, so as to force a check on the permit before issue, since the ICC could be completed many days before the work starts.  Just want to confirm the thought process I had.

2.  Does this need to added?  Can we not use the pre-requisite controls feature and the Permit JHA to manage the requirement for zero-energy verification?  We need to be careful what mandatory checks we build into the system, and how much we change the "Shell" build

3.  Need to check with eVision if there is something similar in their product already?  Have other users requested anything similar?  Would they be interested in building this in to the core product?

**Comment by jimbrown75** [comment]
Dont need if actions get signed off in ICC
