### ISSUE TITLE
Signatures not resetting when permit issued

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#43]
In the system on steps 5, 6 and 7 of the permit details, the signatures of the previous users who signed for actions like Permit Issue, Permit Accept, handover, etc. are not being reset when the permit is issued.  

Here you can see that the permit is LIVE and the signature page seems to have been signed already.  We are expecting to have these signatures reset when the permit is issued and only applied again when the signatures take place after the permit was LIVE.
![not reset](https://user-images.githubusercontent.com/23561839/30671360-bb84f4e8-9e23-11e7-914f-5594cd040925.PNG)

For a full explanation of the expected behaviour please review the attached word file.
[Signature not reset on permit issue.docx](https://github.com/jimbrown75/Permit-Vision-Enhancements/files/1319460/Signature.not.reset.on.permit.issue.docx)

**Comment by jimbrown75** [comment]
This is not just the step 4 initial signature issue that we thought had been fixed by the resource clarification.
