### ISSUE TITLE
Multiple Gas Test Locations for single permit

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#45]
We have a request from Rheinland to be able to have multiple Gas Test Locations on the same permit.  This is in addition to being able to have multiple gas substances (which is already possible).

**CASE FOR CHANGE**:
There are many times in large confiined spaces (towers) when there are many opening/access locations. All would need to be checked to ensure the Confined Space is safe for entry.  Currently you would need a separate permit for each location/access point.  however, typically the same person is responsible for the whole confined space, so it is illogical to expect them to have multiple permits just to manage gas testing.

**EXPECTED RESULT**
- On a single permit the user should be able to define multiple Substance Measurement Locations.  
- Each location should have the full list of substances to test
- Measurements should be recorded against locations and substances.

See mark up example....
![multiple measruer](https://user-images.githubusercontent.com/23561839/30672760-94901518-9e2b-11e7-9b86-79ce59a4f1c0.PNG)

If the user selected YES, then a new area appears which asksd to define Location, then a second appears to define a 2nd, and then a 3rd, etc..... I envisage this to function similar to the Questionnaire Step 13, when user is able to define "Manually entered activities".  The "+Add new activity" is there.  On the Step 2 for substances this could appear as "+Add new location".  Each time "+Add new location" is clicked another text field appears that can have a location name added.  Each would have a delete button as well.
![multiple locations shown](https://user-images.githubusercontent.com/23561839/30673509-d3f6891c-9e30-11e7-93c5-9f9cc8a5ce9a.PNG)

Each of the locations that are added would then have the ability to enter results as defined in the Step 2 Substance required list selections.

**Comment by jimbrown75** [comment]
Just trying to think of how we could use existing functionality to address this without any changes.

You identify the gas test locations in the risk assessment as they are controls.

When you enter the gas test for each location you write the name of the location in the comments field (when they fix it).

Lets discuss

**Comment by jimbrown75** [comment]
Close as we have gas test remark CR in main list
