### ISSUE TITLE
ICC: Add "Squeeze Off" to Isolation Methods

### ISSUE THREAD

**Issue by DANMPV** [jimbrown75/Permit-Vision-Enhancements#47]
The Isolation Method "Squeeze off" is not available in V8 Enterprise Build.  It was added to v7 as an Isolation Method to support work requirements for QGC.  We will be adding QGC to the Enterprise build in 2018, so we need to have this added to v8.

Isolation Type: **Mechanical/Process**
Isolation Method:  **Squeeze Off**
Isolated State: **Squeezed Off**
De-Isolated State: **Open**

![squeeze off](https://user-images.githubusercontent.com/23561839/30821370-5f5f6212-a1e2-11e7-82fd-415fbd5d109c.PNG)

**Comment by jimbrown75** [comment]
similar to #38
